### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by xnko** [manvel-khnkoyan/easy-signature#1]
encode() files silently when crypto module throws an exception, by so how can I be sure that the signature created successfully? I propose to remove try/catch wrapper or inform about failure in another way

**Comment by manvel-khnkoyan** [comment]
Issue was fixed: https://github.com/manvel-khnkoyan/easy-signature/commit/5a892d7a202b81d19b8a8f049af0ade2e996c512

But any case, we do not need to throw an error for validation 
`signature.validate('https://example.com/posts')`
so I surrounded the function _validate_ by  "_try catch_"
